=== rqms/rqms/rqmsmodule-web/src/main/resources/new_admin_config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT admin (modules|mainOrientation)+>
<!ELEMENT mainOrientation (orientationPage+)>
<!ELEMENT modules (module+)>
<!ELEMENT module (folder|page|orientation)*>
<!ELEMENT folder (page+)>
<!ELEMENT page (param*|detailPage*)>
<!ELEMENT param EMPTY>
<!ELEMENT detailPage (param*)>
<!ELEMENT orientation (orientationPage+)>
<!ELEMENT orientationPage EMPTY>


<!ATTLIST module       id CDATA #REQUIRED>
<!ATTLIST module       name CDATA #REQUIRED>
<!ATTLIST module       icon CDATA #REQUIRED>
<!ATTLIST module       url CDATA #REQUIRED>
<!ATTLIST module       hotkey CDATA #IMPLIED>
<!ATTLIST module       license CDATA #IMPLIED>
<!ATTLIST module       service CDATA #IMPLIED>

<!ATTLIST folder       id CDATA #REQUIRED>
<!ATTLIST folder       name CDATA #REQUIRED>
<!ATTLIST folder       icon CDATA #IMPLIED>
<!ATTLIST folder       license CDATA #IMPLIED>
<!ATTLIST folder       bolRootNode CDATA #IMPLIED>

<!ATTLIST page         id CDATA #REQUIRED>
<!ATTLIST page         name CDATA #REQUIRED>
<!ATTLIST page         icon CDATA #IMPLIED>
<!ATTLIST page         url CDATA #REQUIRED>
<!ATTLIST page         license CDATA #IMPLIED>
<!ATTLIST page         DBOwner CDATA #IMPLIED>
<!ATTLIST page         RDBMS CDATA #IMPLIED>
<!ATTLIST page         isNodeRequired CDATA #IMPLIED>
<!ATTLIST page         javaClass CDATA #IMPLIED>



<!ATTLIST param        name CDATA #REQUIRED>
<!ATTLIST param        value CDATA #REQUIRED>

<!ATTLIST detailPage         id CDATA #REQUIRED>
<!ATTLIST detailPage         name CDATA #REQUIRED>
<!ATTLIST detailPage         icon CDATA #IMPLIED>
<!ATTLIST detailPage         url CDATA #REQUIRED>
<!ATTLIST detailPage         license CDATA #IMPLIED>
<!ATTLIST detailPage         DBOwner CDATA #IMPLIED>
<!ATTLIST detailPage         RDBMS CDATA #IMPLIED>
<!ATTLIST detailPage         javaClass CDATA #IMPLIED>

<!ATTLIST orientation		id CDATA #REQUIRED>

<!ATTLIST orientationPage	id CDATA #REQUIRED>
<!ATTLIST orientationPage	name CDATA #REQUIRED>
<!ATTLIST orientationPage	url CDATA #REQUIRED>

=== rqms/rqms/rqmsmodule-web/src/main/resources/new_admin_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules SYSTEM "new_admin_config.dtd">
<!-- Some important information a) Strictly adhere the dtd definition, don't 
	try with new tag or attribute b) If you would like to add new attribute make 
	corresponding changes in AdminConfig.java Aspire 2009/02/04 removed removed 
	the starting "/" in url's [ie: '/admin/layout/address.gif' to 'admin/layout/address.gif'] 
	Aspire 2009/05/26 added licence property for the following modules Asset, 
	Folder, Health, LRProperty, Review and Tax -->
<admin>
	<mainOrientation>
		<!-- <orientationPage id="FolderOrientationConcepts" name="Concepts" url="admin/MainOrientationConcept.jsp" 
			/> <orientationPage id="SiteAndUseAdministration" name="Site and User Administration" 
			url="admin/SiteandUser_AdminOrientation.jsp" /> <orientationPage id="CoreServices" 
			name="Core Services" url="admin/CoreServices_Orientation.jsp" /> <orientationPage 
			id="Module" name="Module" url="admin/ModuleOrientation.jsp" /> -->
		<orientationPage id="FolderOrientationConcepts" name="Concepts"
			url="concepts_orientation.zul" />

		<orientationPage id="SiteAndUseAdministration" name="Site and User Administration"
			url="site_user_admin_orientation.zul" />
		<orientationPage id="CoreServices" name="Core Services"
			url="core_services_orientation.zul" />
		<orientationPage id="Module" name="Module"
			url="module_orientation.zul" />

	</mainOrientation>
	<modules>
		<module id="address" name="Address" icon="admin/layout/address.gif"
			url="admin/groups/orientation.jsp" hotkey="F3" service="core">
			<orientation id="orientation">
				<orientationPage id="AddressOrientation" name="Orientation"
					url="address_orientation.zul" />
			</orientation>

			<page id="ValidProvince" name="Province/State" url="valid_province.zul"
				javaClass="ValidProvince" />


			<page id="ValidCity" name="City" url="valid_city.zul" javaClass="ValidCity" />
			<page id="ValidStreetType" name="Street Type" url="valid_street_type.zul"
				javaClass="ValidStreetType" />
			<page id="ValidStreet" name="Street Name" url="valid_street.zul"
				javaClass="ValidStreet" />
			<page id="ValidCommunity" name="Community" url="valid_community.zul"
				javaClass="ValidCommunity" />
			<page id="ValidCounty_Address" name="County" url="valid_county.zul"
				javaClass="ValidCounty" />
			<page id="ValidCityCommunity" name="City Community" url="valid_city_community.zul"
				javaClass="ValidCityCommunity" />
			<page id="ValidAddressUnitType" name="Unit Type" url="valid_address_unit_type.zul"
				javaClass="ValidAddressUnitType" /><!-- Aspire 2010/03/01 18934 changed 
				the label name on menu pane and tab name -->
			<page id="ValidAddressDirection" name="Direction"
				url="valid_address_direction.zul" javaClass="ValidAddressDirection" /><!-- 
				Aspire 2010/02/18 18935 changed the label name on menu pane and tab name -->
		</module>
	<module id="attachment" name="Attachment" icon="admin/layout/attachment.gif"
			hotkey="F4" url="admin/groups/orientation.jsp" service="core">
			<!-- Aspire 2012/08/13 code added for the enhancement #21610 -->
			<orientation id="orientation">
				<orientationPage id="AttachmentOrientation" name="Orientation"
					url="attachment_orientation.zul" />
			</orientation>
			<page id="ValidAttachment" name="Attachment Type" url="valid_attachment.zul" javaClass="ValidAttachment" />
			<page id="ValidAttachmentInfo" name="Attachment Info"
				url="valid_attachment_info.zul" javaClass="ValidAttachmentInfo"/>
			<!-- Aspire 2012/10/17 - Added Attachment Status for #27375 -->
			<page id="ValidAttachmentStatus" name="Attachment Status"
				url="valid_attachment_status.zul" javaClass="ValidAttachmentStatus"/>
			<page id="ValidAttachmentProcedure" name="Attachment Procedure"
				url="default_procedure.zul" javaClass="DefaultAccountBillFee" >
					
			<param name="where"
				value="ProcedureName = DefaultAttachment_Upd and DefaultDesc = DefaultAttachment_Upd and DefaultOrder = 6667" />
			<param name="HidePasteSQLButtons" value="true" />
		   </page>
				
		</module>


		<module id="foi" name="Access to Information" icon="admin/layout/foi.gif"
			hotkey="F4" url="orientation.zul" service="modules">


			<orientation id="orientation">
				<orientationPage id="FOIOrientation" name="Orientation"
					url="foi_orientation.zul" />
			</orientation>
			<page id="ValidFOICategory" name="FOI Category" url="valid_foi_category.zul"
				javaClass="ValidFoiCategory" />
			<page id="ValidFOIDisposition" name="FOI Disposition" url="valid_foi_disposition.zul"
				javaClass="ValidFoiDisposition" />

			<page id="ValidFOIResult" name="FOI Result" javaClass="ValidFoiResult"
				url="valid_foi_result.zul" />
			<page id="ValidAct" name="Act" url="valid_act.zul" javaClass="ValidAct" />
			<page id="ValidActExtension" name="Act Extension" url="valid_act_extension.zul"
				javaClass="ValidActExtension" />
			<page id="ValidCorrectionMade" name="Correction Made" url="valid_correction_made.zul"
				javaClass="ValidCorrectionMade" />
			<page id="ValidExemption" name="Exemption" url="valid_exemption.zul"
				javaClass="ValidExemption" >
				<param name="orderBy" value="ActCode|ExemptionLabel" />
			</page>
			<page id="ValidExemptionGroup" name="Exemption Group" url="valid_exemption_group.zul"
				javaClass="ValidExemptionGroup" />
			<page id="ValidExtensionGroup" name="Extension Group" url="valid_extension_group.zul"
				javaClass="ValidExtensionGroup" />
			<page id="ValidFinding" name="Finding" url="valid_finding.zul"
				javaClass="ValidFinding" />
			<page id="ValidKeyword" name="Keyword" url="valid_keyword.zul"
				javaClass="ValidKeyword" />
			<page id="ValidLabel" name="Label" url="valid_label.zul"
				javaClass="ValidLabel" />
			<page id="ValidMethodOfAccess" name="Method Of Access" url="valid_method_of_access.zul"
				javaClass="ValidMethodOfAccess" />
			<page id="ValidMethodOfDelivery" name="Method Of Delivery"
				url="valid_method_of_delivery.zul" javaClass="ValidMethodOfDelivery" />
			<page id="ValidOtherReasonsForDenial" name="Other Reasons For Denial"
				url="valid_other_reasons_for_denial.zul" javaClass="ValidOtherReasonsForDenial" />
			<page id="ValidReason" name="Reason" url="valid_reason.zul"
				javaClass="ValidReason" />
			<page id="ValidReasonForDeemedRefusal" name="Reason For Deemed Refusal"
				url="valid_reason_for_deemed_refusal.zul" javaClass="ValidReasonForDeemedRefusal" />
			<page id="ValidRecordGroupStatus" name="Record Group Status"
				url="valid_record_group_status.zul" javaClass="ValidRecordGroupStatus" />
			<page id="ValidRelPkgVersion" name="Rel Pkg Version" url="valid_rel_pkg_version.zul"
				javaClass="ValidRelPkgVersion" />
			<page id="ValidRetentionDisposalRule" name="Retention Disposal Rule"
				url="valid_retention_disposal_rule.zul" javaClass="ValidRetentionDisposalRule" />
			<page id="ValidSource" name="Source" url="valid_source.zul"
				javaClass="ValidSource" />
			<page id="ValidStatute" name="Statute" url="valid_statute.zul"
				javaClass="ValidStatute" />
			<page id="ValidTranslation" name="Translation" url="valid_translation.zul"
				javaClass="ValidTranslation" />




		</module>


		<module id="assetManagement" name="Asset Management"
			icon="admin/layout/asset_management.gif" hotkey=""
			url="admin/groups/orientation.jsp" service="modules" license="Asset">
			<!-- Aspire 2010/02/15 - Nodes ordered as per robb's suggestion -->
			<page id="ValidAsset" name="Asset" url="ValidAsset.zul"
				javaClass="ValidAsset" />
			<page id="ValidAssetCategory" name="Category"
				url="admin/ValidAssetCategory.jsp" javaClass="ValidAsset" />
			<page id="ValidAssetCategorySub" name="Category Sub"
				url="admin/ValidAssetCategorySub.jsp" javaClass="ValidAsset" />
			<page id="ValidAssetClass" name="Class" url="admin/ValidAssetClass.jsp"
				javaClass="ValidAsset" />
			<page id="ValidAssetClassSub" name="Class Sub"
				url="admin/ValidAssetClassSub.jsp" javaClass="ValidAsset" />
			<page id="ValidAssetGroup" name="Group" url="admin/ValidAssetGroup.jsp"
				javaClass="ValidAsset" />
			<page id="ValidAssetGroupSub" name="Group Sub"
				url="admin/ValidAssetGroupSub.jsp" javaClass="ValidAsset" />
			<page id="ValidAssetWoGroup" name="WO Group" url="admin/ValidAssetWoGroup.jsp" />
			<page id="ValidAssetWoGroupSub" name="WO Group Sub"
				url="admin/ValidAssetWoGroupSub.jsp" />
			<page id="ValidAssetCondition" name="Condition"
				url="admin/ValidAssetCondition.jsp" javaClass="ValidAsset" />
			<page id="ValidAssetContract" name="Contract"
				url="admin/ValidAssetContract.jsp" javaClass="ValidAsset" />
			<page id="ValidAssetAcquisitionMethod" name="Acquisition Method"
				url="admin/ValidAssetAcquisitionMethod.jsp" javaClass="ValidAsset" />
			<page id="ValidAssetDisposition" name="Disposition"
				url="admin/ValidAssetDisposition.jsp" javaClass="ValidAsset" />
			<page id="ValidAssetQualification" name="Qualification"
				url="admin/ValidAssetQualification.jsp" javaClass="ValidAsset" />
			<!-- Aspire 2011/09/05 - ValidAssetRate does not exist for Asset -->
			<!-- <page id="ValidAssetRate" name="Rate" url="admin/ValidAssetRate.jsp" 
				/> -->
			<page id="ValidAssetStatus" name="Status" url="admin/ValidAssetStatus.jsp"
				javaClass="ValidAsset" />
			<page id="ValidAssetUnit" name="Asset Unit" url="admin/ValidAssetUnit.jsp"
				javaClass="ValidAsset" />
			<page id="ValidAssetUnitConversion" name="Asset Unit Conversion"
				url="admin/ValidAssetUnitConversion.jsp" />
			<page id="ValidChartOfGlAccount" name="GL Account"
				url="ValidChartOfGlAccount.zul" javaClass="ValidChartOfGlAccount" />
			<page id="ValidLocationBuilding" name="Location Building"
				url="ValidLocationBuilding.zul" javaClass="ValidLocationBuilding" />
			<page id="ValidLocationDepartment" name="Location Department"
				url="ValidLocationDepartment.zul" javaClass="ValidLocationDepartment" />
